# Generated by Django 5.0.1 on 2024-01-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="This is a blog ", max_length=255),
        ),
    ]
