# Generated by Django 5.0.1 on 2024-01-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0009_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/prorile"),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="website_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
