# Generated by Django 5.0.1 on 2024-01-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0012_alter_post_title_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
